### ISSUE TITLE
[ENHANCEMENT] Add more tests

### ISSUE THREAD

**Issue by ElBe-Plaq** [I-Language-Development/I-language#18]
Add more pytest tests to cover most parts of the code.

Current coverage: 50%

**Todo:**
- [ ] Add tests for `ilanguage\Main\_ast.py`
- [ ] Add tests for `ilanguage\Main\_errors.py`
- [ ] Add tests for `ilanguage\Main\_types.py`
- [ ] Add tests for `ilanguage\Main\lexer.py`
- [ ] Add tests for `ilanguage\Main\shell.py`
- [ ] Add tests for `ilanguage\Modules\_core\Console.py`
- [ ] Add tests for `ilanguage\Modules\_core\Math.py`
- [ ] Add tests for `ilanguage\Modules\_core\Random.py`
- [ ] Add tests for `ilanguage\__init__.py`
- [ ] Add tests for `ilanguage\__main__.py`

**Comment by ElBe-Plaq** [comment]
Tests will be done by @Ranastra, I'll do the cleanups and stuff.
